version: 0.2

env:
    variables:
        IMAGE_TAG: 2.0.0

phases:
    pre_build:
        commands:
            - aws --version
            - PROJECT_NAME=php-runtime
            - echo ${DOCKER_HUB_PASSWORD} | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
    build:
        commands:
            - make publish PROJECT_NAME=${PROJECT_NAME} IMAGE_TAG=${IMAGE_TAG}
